package corbaBanque;


/**
* corbaBanque/IBanqueRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* jeudi 13 novembre 2025 19 h 03 WAT
*/


// ÙÆØ§Ø¬Ù!Ø© Ø§ÙØ¨Ù Ù?
public interface IBanqueRemoteOperations 
{

  // Ø¥Ù Ø´Ø§Ø¡ Ø­Ø³Ø§Ø¨
  void creerCompte (corbaBanque.Compte cpte);

  // Ø¥Ù`Ø¯Ø§Ø¹ Ù&Ø¨ÙØº ÙýÙ` Ø­Ø³Ø§Ø¨
  void verser (float mt, int code);

  // Ø³Ø­Ø¨ Ù&Ø¨ÙØº Ù&Ù  Ø­Ø³Ø§Ø¨
  void retirer (float mt, int code);

  // Ø§ÙØ­ØµÙÆÙ Ø¹ÙÙ0 Ø­Ø³Ø§Ø¨ Ù&Ø¹Ù`Ù
  corbaBanque.Compte getCompte (int code);

  // Ø§ÙØ­ØµÙÆÙ Ø¹ÙÙ0 Ø¬Ù&Ù`Ø¹ Ø§ÙØ­Ø³Ø§Ø¨Ø§Øª
  corbaBanque.Compte[] getComptes ();

  // ØªØ­ÙÆÙ`Ù Ø§ÙÙ`ÙÆØ±ÙÆ Ø¥ÙÙ0 Ø¯Ù`Ù Ø§Ø±
  double conversion (float mt);
} // interface IBanqueRemoteOperations
